extends:
  - react-app
parserOptions:
  project: ./tsconfig.json
overrides:
  - files:
      - vite.config.ts
    parserOptions:
      project: ./tsconfig.node.json
rules:
  no-console:
    - error
    - allow:
        - info
        - error
        - warn
  '@typescript-eslint/no-restricted-imports':
    - error
    - patterns:
        - group:
            - '@app/backend/**'
            - '!@app/backend/**/'
            - '!@app/backend/**/input'
            - '!@app/backend/src/utils/can'
          allowTypeImports: true
          message: 'Only types and input schemas are allowed to be imported from backend workspace'